apiVersion: 1

datasources:
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: k6
    user: k6user
    secureJsonData:
      password: k6password
    jsonData:
      httpMode: GET
    editable: true
